### ISSUE TITLE
Sub-Files not Extracted

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-oletools#58]
When the oletools service times out, sub-files that were extracted that had `FILES_OF_INTEREST` extensions are not returned. I'm not sure, but I believe the oletools VBA_Parser time out errors are causing the issue. If one portion of the oletools service fails, I would hope that the faster results would still be included.

If the extract service is configured to process `document/office/.*` files, the extract service skips any file that is not encrypted. If the extract service was modified to extract `document/office/.*` files, it could have a `FILES_OF_INTEREST` parameter to limit the extracted files.

**Comment by cccs-jh** [comment]
Unfortunately the only current way to return partial results is to ensure the service never times out by manually enforcing time limits from within the service. Because of the complexity that would add this is not currently planned for oletools.

While extract could extract some files from OOXML based office documents based on file extension, I don't think it is a great solution.  It wouldn't be able to handle OLE streams, which don't have a file extension and would only extract a subset of what oletools currently extracts. Oletools would have to process the same files anyway leading to duplication.
